import puppeteer, { Browser, Page } from "puppeteer";
import chromium from "@sparticuz/chromium";

let browserPromise: Promise<Browser> | null = null;

export async function getShopeeBrowser(): Promise<Browser> {
  if (!browserPromise) {
    const browserlessEndpoint = process.env.BROWSERLESS_WS_ENDPOINT;
    browserPromise = (async () => {
      if (browserlessEndpoint) return puppeteer.connect({ browserWSEndpoint: browserlessEndpoint });
      const serverless = Boolean(process.env.VERCEL || process.env.AWS_LAMBDA_FUNCTION_NAME);
      return puppeteer.launch({
        headless: serverless ? "shell" : true,
        executablePath:
          process.env.PUPPETEER_EXECUTABLE_PATH || (serverless ? await chromium.executablePath() : undefined),
        args: [
          ...(serverless ? chromium.args : []),
          "--no-sandbox",
          "--disable-setuid-sandbox",
          "--disable-dev-shm-usage",
          "--disable-blink-features=AutomationControlled",
          "--disable-features=IsolateOrigins,site-per-process",
        ],
      });
    })();
    const currentBrowserPromise = browserPromise;
    void currentBrowserPromise
      .then((browser) => browser.once("disconnected", () => {
        if (browserPromise === currentBrowserPromise) browserPromise = null;
      }))
      .catch(() => {
        if (browserPromise === currentBrowserPromise) browserPromise = null;
      });
  }
  return browserPromise;
}

export interface ShopeeScrapedProduct {
  name: string;
  image: string;
  price: number;
  priceMax: number;
  sold: number;
  ratingStar: number;
  ratingCount: number;
}

/**
 * Scrape product info from Shopee using a real browser (Puppeteer).
 * Bypasses anti-bot since it executes the page's JavaScript.
 */
export async function scrapeShopeeProduct(
  shopId: number,
  itemId: number,
  originalUrl?: string
): Promise<ShopeeScrapedProduct | null> {
  let page: Page | null = null;
  try {
    const browser = await getShopeeBrowser();
    page = await browser.newPage();

    // Set realistic viewport and UA
    await page.setUserAgent(
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36"
    );
    await page.setViewport({ width: 1366, height: 768 });

    // Block heavy resources to speed up loading
    await page.setRequestInterception(true);
    page.on("request", (req) => {
      const type = req.resourceType();
      if (type === "image" || type === "media" || type === "font") {
        req.abort();
      } else {
        req.continue();
      }
    });

    // Hide automation fingerprints
    await page.evaluateOnNewDocument(() => {
      Object.defineProperty(navigator, "webdriver", { get: () => undefined });
      Object.defineProperty(navigator, "languages", { get: () => ["vi-VN", "vi", "en"] });
    });

    // Navigate to Shopee homepage first - guaranteed to load without redirect issues.
    // Once the page is loaded, we can call /api/v4/item/get from within the page context
    // (same-origin) which bypasses anti-bot since we're a real browser on shopee.vn.
    await page.goto("https://shopee.vn/", { waitUntil: "domcontentloaded", timeout: 20000 });

    // Wait a bit for Shopee's anti-bot tokens to be generated by their JS
    await new Promise((r) => setTimeout(r, 1500));

    // Call Shopee's internal API from within the page context.
    const data = await page.evaluate(async (sid, iid) => {
      try {
        const res = await fetch(`/api/v4/item/get?shopid=${sid}&itemid=${iid}`, {
          headers: {
            "x-api-source": "pc",
            "x-shopee-language": "vi",
            "x-requested-with": "XMLHttpRequest",
          },
          credentials: "include",
        });
        if (!res.ok) return { error: res.status };
        const json = await res.json();
        return json?.data || { error: "no data", json };
      } catch (e: any) {
        return { error: String(e) };
      }
    }, shopId, itemId);

    if (data && (data as any).error) {
      console.log("Shopee in-page API error:", JSON.stringify(data).slice(0, 200));
      // Reset data so we fall through to DOM scrape fallback
      Object.keys(data as any).forEach((k) => delete (data as any)[k]);
    }

    if (data && (data as any).name) {
      const price = Math.floor((data.price || data.price_min || 0) / 100000);
      const priceMax = Math.floor((data.price_max || data.price || 0) / 100000);
      const imageHash = data.image || (data.images && data.images[0]) || "";
      const image = imageHash
        ? `https://down-vn.img.susercontent.com/file/${imageHash}`
        : "";
      return {
        name: data.name || "",
        image,
        price,
        priceMax,
        sold: data.sold || data.historical_sold || 0,
        ratingStar: data.item_rating?.rating_star || 0,
        ratingCount: data.item_rating?.rating_count?.[0] || 0,
      };
    }

    // Fallback: scrape DOM after waiting for it to render
    await page.waitForSelector('div[class*="product-briefing"]', { timeout: 8000 }).catch(() => {});

    const scraped = await page.evaluate(() => {
      const getMeta = (prop: string) => {
        const el = document.querySelector(`meta[property="${prop}"], meta[name="${prop}"]`);
        return el?.getAttribute("content") || "";
      };
      const ogTitle = getMeta("og:title");
      const ogImage = getMeta("og:image");
      const ogDesc = getMeta("og:description");

      // Extract price from page text
      const priceText = document.body.innerText.match(/₫\s*([\d.,]+)/);
      const price = priceText ? parseInt(priceText[1].replace(/[.,]/g, "")) : 0;

      return {
        name: ogTitle.replace(/\s*\|\s*Shopee.*$/, "").trim() || "",
        image: ogImage || "",
        description: ogDesc || "",
        price,
      };
    });

    if (scraped.name) {
      return {
        name: scraped.name,
        image: scraped.image,
        price: scraped.price,
        priceMax: scraped.price,
        sold: 0,
        ratingStar: 0,
        ratingCount: 0,
      };
    }

    return null;
  } catch (e) {
    console.error("Shopee scrape error:", e);
    return null;
  } finally {
    if (page) await page.close().catch(() => {});
  }
}
